"""Guard: params library hygiene — name uniqueness, alias alignment, orphan baseline.

Parameterized from ``config/quality/params-modules.json`` (generated by a
one-time scan of ``src/l1/kernel/params/``). The test compares against the
snapshot instead of re-scanning the entire codebase — faster and not
Python-runtime-dependent.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SNAPSHOT_PATH = ROOT / "config" / "quality" / "params-modules.json"

# Load the snapshot once at module level.
_SNAPSHOT: dict | None = None


def _snapshot() -> dict:
    global _SNAPSHOT
    if _SNAPSHOT is None:
        _SNAPSHOT = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
    return _SNAPSHOT


def test_no_duplicate_names_across_modules() -> None:
    """A constant name must be defined in exactly one params module."""
    from collections import defaultdict

    byname: dict[str, list[str]] = defaultdict(list)
    for mod, names in _snapshot()["module_names"].items():
        for n in names:
            byname[n].append(mod)
    dups = {n: ms for n, ms in byname.items() if len(ms) > 1}
    assert not dups, f"constants defined in multiple modules: {dups}"


def test_known_duplicate_pairs_stay_aligned() -> None:
    """The unified duplicate pairs must stay value-aligned (alias pattern)."""
    from l1.kernel.params.allocator import ALLOCATOR_DEFAULTS
    from l1.kernel.params.api import GIT_TIMEOUT, NOTIFY_WEBHOOK_TIMEOUT, TOOL_WEBHOOK_TIMEOUT
    from l1.kernel.params.system import RING1_CAPACITY, RING2_CAPACITY, RING3_CAPACITY
    from l1.kernel.params.tool import TOOL_GIT_TIMEOUT

    assert GIT_TIMEOUT == TOOL_GIT_TIMEOUT, "GIT_TIMEOUT must alias TOOL_GIT_TIMEOUT"
    assert NOTIFY_WEBHOOK_TIMEOUT == TOOL_WEBHOOK_TIMEOUT, "NOTIFY_WEBHOOK_TIMEOUT must alias TOOL_WEBHOOK_TIMEOUT"
    assert ALLOCATOR_DEFAULTS.ring1 == RING1_CAPACITY
    assert ALLOCATOR_DEFAULTS.ring2 == RING2_CAPACITY
    assert ALLOCATOR_DEFAULTS.ring3 == RING3_CAPACITY
    import l1.kernel.params.api as _api

    assert not hasattr(_api, "API_GATEWAY_DEFAULT_PORT"), "dead twin API_GATEWAY_DEFAULT_PORT resurfaced"


def test_orphan_constants_do_not_grow() -> None:
    """Dead constants must stay within the known-debt ledger (shrink-only).

    The ledger is pre-computed from a full-codebase scan and stored in
    ``config/quality/params-modules.json``. New constants added to the
    params directory are NOT in the snapshot, so they must be referenced
    somewhere in the codebase or the test will fail.
    """
    known = set(_snapshot()["dead_orphans"])
    ledger = set(_snapshot()["ledger_orphans"])

    # Check that all known dead constants are in the ledger.
    unknowns = known - ledger
    assert not unknowns, (
        f"constants dead but not in ledger (add to BASELINE_DEAD_ORPHANS): "
        f"{sorted(unknowns)}"
    )

    # Check that the ledger hasn't grown (shrink-only policy).
    # Constants that are now alive (referenced) but still in the ledger
    # are acceptable (the ledger is a superset).
    # The key gate: no NEW dead constants beyond the ledger.
    excess = known - ledger
    assert not excess, (
        f"new dead constants beyond known ledger: {sorted(excess)}"
    )